import type { Metadata } from 'next';
import styles from './test.module.scss'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className={`${styles.test} text-sky-500`}>你好</div>
  );
}
