import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className={` text-sky-500 dark:text-white`} >你好</div>
  );
}
